version: '2'

services:

  postgres:
    image: postgres:9.5
    environment:
      POSTGRES_USER: sequelize_slugify_test
      POSTGRES_PASSWORD: sequelize_slugify_test
      POSTGRES_DB: sequelize_slugify_test
    ports:
      - "8195:5432"
    container_name: postgres-95

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sequelize_slugify_test
      MYSQL_USER: sequelize_slugify_test
      MYSQL_PASSWORD: sequelize_slugify_test
    ports:
      - "8257:3306"
    container_name: mysql-57

  mariadb:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sequelize_slugify_test
      MYSQL_USER: sequelize_slugify_test
      MYSQL_PASSWORD: sequelize_slugify_test
    ports:
      - "8313:3306"
    container_name: mariadb-106

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Sequelize22Slugify"
    ports:
      - "8400:1433"
    container_name: mssql-2022
